import { validationResult } from "express-validator";

/**
 * Return validation errors generated by express-validator.
 *
 * Place this middleware after validation rules and before the controller.
 */
export const validateRequest = (req, res, next) => {
  const errors = validationResult(req);

  if (errors.isEmpty()) {
    return next();
  }

  const formattedErrors = errors.array().map((error) => ({
    field: error.path || error.param || "unknown",
    message: error.msg,
    value: error.value,
    location: error.location,
  }));

  return res.status(400).json({
    success: false,
    message: "Validation failed.",
    errors: formattedErrors,
  });
};